version: '3.4'

services:
  bds:
    container_name: minecraft-my-server
    build:
      context: custom-bds
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      WHITE_LIST: "true"
    ports:
      - 19132:19132/udp
    volumes:
      - ./bds:/data
    stdin_open: true
    tty: true
    stop_grace_period: 10m00s
    restart: "always"
